##Script to merge temperature data from alpine lakes.

library(xts)
source("~/code/MORA_microclimate/air_temp_functions.R")

####Read in data.####
setwd("~/Dropbox/Lab/EcoForecasting_SDD_Phenology (1)/Data&Analysis/Microclimate/raw/Rebecca/assembled/")

al_por <- read.csv("Allen_airtemperature_thru_2013.csv")
al_por$Datetime <- as.POSIXct(al_por$Date.time,format="%m/%d/%y %H:%M")
al_2014 <- read.csv("Allen_airtemperature_2013_2014.csv")
al_2014$Date <- as.character(as.Date(al_2014$Date,format="%m/%d/%y"))
al_2014$Datetime <- as.POSIXct(paste(al_2014$Date,al_2014$Time),format="%Y-%m-%d %I:%M:%S %p")
al_2015 <- read.csv("Allen_airtemperature_2014_2015.csv")
al_2015$Datetime <- as.POSIXct(paste(al_2015$Date,al_2015$Time),format="%m/%d/%y %H:%M:%S")
al_dt <- c(al_por$Datetime,al_2014$Datetime,al_2015$Datetime)
al_t <- c(al_por$Temp,al_2014$Temp,al_2015$Temp)
al_all <- data.frame(Datetime=al_dt,Temp=al_t)
write.csv(al_all,"../merged/Allen_airtemperature_all.csv",row.names=FALSE)

al_ts <- xts(al_all$Temp,order.by=al_all$Datetime)
al_ts_cleaned <- remove_spikes(al_ts,ts_lag=2,thresh=c(-5,5))
al_df_cleaned <- data.frame(Datetime=index(al_ts_cleaned),Temp=al_ts_cleaned)
write.csv(al_df_cleaned,"../cleaned/Allen_airtemp_all_cleaned.csv")

bl_por <- read.csv("Blue_airtemperature_thru_2013.csv")
bl_por$Datetime <- as.POSIXct(bl_por$Date.time,format="%m/%d/%y %H:%M")
bl_2014 <- read.csv("Blue_airtemperature_2013_2014.csv")
bl_2014$Datetime <- as.POSIXct(paste(bl_2014$Date,bl_2014$Time),format="%m/%d/%y %H:%M")
bl_2015 <- read.csv("Blue_airtemperature_2014_2015.csv")
bl_2015$Datetime <- as.POSIXct(paste(bl_2015$Date,bl_2015$Time),format="%m/%d/%y %H:%M:%S")
bl_dt <- c(bl_por$Datetime,bl_2014$Datetime,bl_2015$Datetime)
bl_t <- c(bl_por$Temp,bl_2014$Temp,bl_2015$Temp)
bl_all <- data.frame(Datetime=bl_dt,Temp=bl_t)
write.csv(bl_all,"Blue_airtemperature_all.csv",row.names=FALSE)

bl_ts <- xts(bl_all$Temp,order.by=bl_all$Datetime)
bl_ts_cleaned <- remove_spikes(bl_ts,ts_lag=1,thresh=c(-5,5))
bl_df_cleaned <- data.frame(Datetime=index(bl_ts_cleaned),Temp=bl_ts_cleaned)
write.csv(bl_df_cleaned,"../cleaned/Blue_airtemp_all_cleaned.csv")

dw_por <- read.csv("Deadwood_airtemperature_thru_2013.csv")
dw_por$Datetime <- as.POSIXct(dw_por$Date.time,format="%m/%d/%y %H:%M")
dw_2014 <- read.csv("Deadwood_airtemperature_2013_2014.csv")
dw_2014$Datetime <- as.POSIXct(paste(dw_2014$Date,dw_2014$time,dw_2014$X),format="%m/%d/%y %I:%M:%S %p")
dw_2015 <- read.csv("Deadwood_airtemperature_2014_2015.csv")
dw_2015$Datetime <- as.POSIXct(paste(dw_2015$Date,dw_2015$time),format="%m/%d/%y %H:%M:%S")
dw_dt <- c(dw_por$Datetime,dw_2014$Datetime,dw_2015$Datetime)
dw_t <- c(dw_por$Temp,dw_2014$Temp,dw_2015$Temp)
dw_all <- data.frame(Datetime=dw_dt,Temp=dw_t)
write.csv(dw_all,"Deadwood_airtemperature_all.csv",row.names=FALSE)

dw_ts <- xts(dw_all$Temp,order.by=dw_all$Datetime)
dw_ts_cleaned <- remove_spikes(dw_ts,ts_lag=2,thresh=c(-5,5))
dw_df_cleaned <- data.frame(Datetime=index(dw_ts_cleaned),Temp=dw_ts_cleaned)
write.csv(dw_df_cleaned,"../cleaned/Deadwood_airtemp_all_cleaned.csv")


lh15_por <- read.csv("lh15_airtemperature_thru_2013.csv")
lh15_por$Datetime <- as.POSIXct(lh15_por$Date.Time,format="%m/%d/%y %H:%M")
lh15_2014 <- read.csv("lh15_airtemperature_2013_2014.csv")
lh15_2014$Datetime <- as.POSIXct(lh15_2014$Date,format="%m/%d/%y %H:%M")
lh15_2015 <- read.csv("lh15_airtemperature_2014_2015.csv")
lh15_2015$Datetime <- as.POSIXct(paste(lh15_2015$Date,lh15_2015$Time),format="%m/%d/%y %H:%M:%S")
lh15_dt <- c(lh15_por$Datetime,lh15_2014$Datetime,lh15_2015$Datetime)
lh15_t <- c(lh15_por$Temp,lh15_2014$Temp,lh15_2015$Ave.Temp.C)
lh15_all <- data.frame(Datetime=lh15_dt,Temp=lh15_t)
write.csv(lh15_all,"lh15_airtemperature_all.csv",row.names=FALSE)

lh15_ts <- xts(lh15_all$Temp,order.by=lh15_all$Datetime)
lh15_ts_cleaned <- remove_spikes(lh15_ts,ts_lag=1,thresh=c(-3,3))
lh15_df_cleaned <- data.frame(Datetime=index(lh15_ts_cleaned),Temp=lh15_ts_cleaned)
write.csv(lh15_df_cleaned,"../cleaned/lh15_airtemp_all_cleaned.csv")

lp19_por <- read.csv("lp19_airtemperature_thru_2013.csv")
lp19_por$Datetime <- as.POSIXct(lp19_por$Date.Time,format="%m/%d/%y %H:%M")
lp19_2014 <- read.csv("lp19_airtemperature_2013_2014.csv")
lp19_2014$Datetime <- as.POSIXct(paste(lp19_2014$Date,lp19_2014$Time),format="%m/%d/%y %H:%M")
lp19_2015 <- read.csv("lp19_airtemperature_2014_2015.csv")
lp19_2015$Datetime <- as.POSIXct(paste(lp19_2015$Date,lp19_2015$Time),format="%m/%d/%y %H:%M:%S")
lp19_dt <- c(lp19_por$Datetime,lp19_2014$Datetime,lp19_2015$Datetime)
lp19_t <- c(lp19_por$Temp,lp19_2014$Temp,lp19_2015$Temp)
lp19_all <- data.frame(Datetime=lp19_dt,Temp=lp19_t)
write.csv(lp19_all,"lp19_airtemperature_all.csv",row.names=FALSE)

lp19_ts <- xts(lp19_all$Temp,order.by=lp19_all$Datetime)
lp19_ts_cleaned <- remove_spikes(lp19_ts,ts_lag=2,thresh=c(-5,5))
lp19_df_cleaned <- data.frame(Datetime=index(lp19_ts_cleaned),Temp=lp19_ts_cleaned)
write.csv(lp19_df_cleaned,"../cleaned/lp19_airtemp_all_cleaned.csv")

upl_2014 <- read.csv("UpperPalisades_airtemperature_2013_2014.csv")
upl_2014$Datetime <- as.POSIXct(paste(upl_2014$Date,upl_2014$Time),format="%m/%d/%y %H:%M")
upl_2015 <- read.csv("UpperPalisades_airtemperature_2014_2015.csv")
upl_2015$Datetime <- as.POSIXct(paste(upl_2015$Date,upl_2015$Time),format="%m/%d/%y %H:%M:%S")
upl_dt <- c(upl_2014$Datetime,upl_2015$Datetime)
upl_t <- c(upl_2014$Temp,upl_2015$Temp)
upl_all <- data.frame(Datetime=upl_dt,Temp=upl_t)
write.csv(upl_all,"UpperPalisades_airtemperature_all.csv",row.names=FALSE)

upl_ts <- xts(upl_all$Temp,order.by=upl_all$Datetime)
upl_ts_cleaned <- remove_spikes(upl_ts,ts_lag=2,thresh=c(-5,5))
upl_df_cleaned <- data.frame(Datetime=index(upl_ts_cleaned),Temp=upl_ts_cleaned)
write.csv(upl_df_cleaned,"../cleaned/UpperPalisades_airtemp_all_cleaned.csv")

#Checks alignment
start <- as.POSIXct("2014-10-01")
end <- as.POSIXct("2014-11-14")
plot(al_df_cleaned,type="l",xlim=c(start,end))
axis.POSIXct(1,seq(start,end,by='day'))
points(bl_df_cleaned$Datetime,bl_df_cleaned$Temp,col=2,type="l")
points(dw_df_cleaned$Datetime,dw_df_cleaned$Temp,col=3,type="l")
points(lh15_df_cleaned$Datetime,lh15_df_cleaned$Temp,col=4,type="l")
points(lp19_df_cleaned$Datetime,lp19_df_cleaned$Temp,col=5,type="l")
points(upl_df_cleaned$Datetime,upl_df_cleaned$Temp,col=6,type="l")

##Takes only measurements on the hour.
all_ts_hrs <- seq(as.POSIXct("2008-09-12 00:00"),as.POSIXct("2015-10-02 00:00"),by="hour")
all_hrs_df <- data.frame(Datetime=all_ts_hrs)

all_hrs_al <- unique(merge(all_hrs_df,al_df_cleaned,by="Datetime",all.x=TRUE))
all_hrs_bl <- unique(merge(all_hrs_al,bl_df_cleaned,by="Datetime",all.x=TRUE))
all_hrs_dw <- unique(merge(all_hrs_bl,dw_df_cleaned,by="Datetime",all.x=TRUE))
all_hrs_lh15 <- unique(merge(all_hrs_dw,lh15_df_cleaned,by="Datetime",all.x=TRUE))
all_hrs_lp19 <- unique(merge(all_hrs_lh15,lp19_df_cleaned,by="Datetime",all.x=TRUE))
all_hrly <- unique(merge(all_hrs_lp19,upl_df_cleaned,by="Datetime",all.x=TRUE))
colnames(all_hrly) <- c("Datetime","Allen","Blue","Deadwood","LH15","LP19","UpperPalisades")
write.csv(all_hrly,"../cleaned/airtemp_all_sites_hourly.csv",row.names=FALSE)

#Checks alignment again
start <- as.POSIXct("2014-8-01")
end <- as.POSIXct("2014-9-14")
plot(all_hrly$Datetime,all_hrly$Allen,type="l",xlim=c(start,end))
axis.POSIXct(1,seq(start,end,by='day'))
points(all_hrly$Datetime,all_hrly$Blue,col=2,type="l")
points(all_hrly$Datetime,all_hrly$Deadwood,col=3,type="l")
points(all_hrly$Datetime,all_hrly$LH15,col=4,type="l")
points(all_hrly$Datetime,all_hrly$LP19,col=5,type="l")
points(all_hrly$Datetime,all_hrly$UpperPalisades,col=6,type="l")

##Calculates daily statistics from hourly.
all_hrly_ts <- xts(x=all_hrly[,-1],order.by=all_hrly$Datetime)
days <- seq(as.POSIXct("2008-09-12 00:00"),as.POSIXct("2015-10-02 00:00"),by="day")
all_daily_max <- matrix(NA,nrow=length(days),ncol=ncol(all_hrly_ts))
all_daily_min <- matrix(NA,nrow=length(days),ncol=ncol(all_hrly_ts))
all_daily_mean <- matrix(NA,nrow=length(days),ncol=ncol(all_hrly_ts))
for(i in 1:ncol(all_hrly_ts)){
  all_daily_max[,i] <- apply.daily(all_hrly_ts[,i],FUN=max)
  all_daily_min[,i] <- apply.daily(all_hrly_ts[,i],FUN=min)
  all_daily_mean[,i] <- apply.daily(all_hrly_ts[,i],FUN=mean)
}
all_daily_tmax <- data.frame(days,all_daily_max)
colnames(all_daily_tmax) <- c("Datetime","Allen","Blue","Deadwood","LH15","LP19","UpperPalisades")
all_daily_tmin <- data.frame(days,all_daily_min)
colnames(all_daily_tmin) <- c("Datetime","Allen","Blue","Deadwood","LH15","LP19","UpperPalisades")
all_daily_tavg <- data.frame(days,all_daily_mean)
colnames(all_daily_tavg) <- c("Datetime","Allen","Blue","Deadwood","LH15","LP19","UpperPalisades")

write.csv(all_daily_tmax,"../cleaned/airtemp_all_daily_tmax.csv",row.names=FALSE)
write.csv(all_daily_tmin,"../cleaned/airtemp_all_daily_tmin.csv",row.names=FALSE)
write.csv(all_daily_tavg,"../cleaned/airtemp_all_daily_tavg.csv",row.names=FALSE)

##Checks data one more time.
start <- as.POSIXct("2010-10-01")
end <- as.POSIXct("2015-9-30")
all_daily_tmax_ts <- xts(x=as.matrix(all_daily_tmax[,-1]),order.by=all_daily_tmax[,1])
all_daily_tmin_ts <- xts(x=as.matrix(all_daily_tmin[,-1]),order.by=all_daily_tmin[,1])
all_daily_tavg_ts <- xts(x=as.matrix(all_daily_tavg[,-1]),order.by=all_daily_tavg[,1])

plot(all_daily_tmax_ts[,1],lty=1,xlim=c(start,end))
points(all_daily_tmax_ts[,2],col=2,lty=1,type="l")
points(all_daily_tmax_ts[,3],col=3,lty=1,type="l")
points(all_daily_tmax_ts[,4],col=4,lty=1,type="l")
points(all_daily_tmax_ts[,5],col=5,lty=1,type="l")
points(all_daily_tmax_ts[,6],col=6,lty=1,type="l")

# points(all_daily_tmin_ts[,1],col=1,lty=3,type="l")
# points(all_daily_tmin_ts[,2],col=2,lty=3,type="l")
# points(all_daily_tmin_ts[,3],col=3,lty=3,type="l")
# points(all_daily_tmin_ts[,4],col=4,lty=3,type="l")
# points(all_daily_tmin_ts[,5],col=5,lty=3,type="l")
# points(all_daily_tmin_ts[,6],col=6,lty=3,type="l")
# 
# points(all_daily_tavg_ts[,1],col=1,lty=1,type="l")
# points(all_daily_tavg_ts[,2],col=2,lty=1,type="l")
# points(all_daily_tavg_ts[,3],col=3,lty=1,type="l")
# points(all_daily_tavg_ts[,4],col=4,lty=1,type="l")
# points(all_daily_tavg_ts[,5],col=5,lty=1,type="l")
# points(all_daily_tavg_ts[,6],col=6,lty=1,type="l")

